### ISSUE TITLE
fix(recorder): main is red — nix::sys::signal used without the nix "signal" feature (#416)

### ISSUE THREAD

**Issue by vibechoom** [vibec0re/trollshell#464]
## main does not compile — `recorder.rs` uses `nix::sys::signal` but the `nix` dep only enables `["fs"]`

`origin/main` at `1f043f6` fails `cargo build/clippy/test --workspace` in the devShell:

```
error[E0433]: cannot find `Signal` in `signal`
error[E0425]: cannot find function `kill` in module `nix::sys::signal`
  --> crates/hytte-services/src/recorder.rs:342
error: could not compile `hytte-services` (lib) due to 3 previous errors
```

### Cause

`recorder.rs` (from #416, `interrupt()`) calls `nix::sys::signal::kill(pid, nix::sys::signal::Signal::SIGINT)`, but `crates/hytte-services/Cargo.toml` declares:

```toml
nix = { version = "0.29", default-features = false, features = ["fs"] }
```

The `nix::sys::signal` module is gated behind the crate's `signal` feature, which nothing in the workspace enables (`cargo tree -e features -i nix` shows only `fs`). `recorder` is `pub mod recorder;` (unconditional), so this is a hard error on the default build, not just `--all-targets`.

This is the "merge-order combined-tree red" pattern — #416 landed green in isolation (CI does not run the clippy/build gate) but left `main` red.

### Fix (one line)

```toml
nix = { version = "0.29", default-features = false, features = ["fs", "signal"] }
```

Verified locally: with `"signal"` added, `cargo clippy --workspace --all-targets -- -D warnings`, `cargo build --workspace`, and `cargo test --workspace` (495 passed) are all green.

### Note

Surfaced while fixing #420 (PR #463), which touches only `idle_notify.rs` and is clean in isolation but can't get a green full-workspace gate until this lands. Worth a fast hotfix PR.
